[package]
name = "fibonacci"
version = "0.2.0"
authors = ["hernad"]
build = "build.rs"

[lib]
name = "fibonacci"
crate-type = ["dylib"]

[[bin]]
name = "fibonacci-bin"
path = "bin/main.rs"


[dependencies]


[build-dependencies]
cc = "1.0.18"


[features]
default = ["foo"]
foo = []
bar = []
