[package]
name = "fibonacci"
version = "0.2.0"
authors = ["hernad"]
build = "build.rs"

[lib]
name = "fibonacci"
crate-type = ["dylib"]

[dependencies]


[build-dependencies]
cc = "1.0.18"


[features]
default = ["foo"]
foo = []
bar = []
